language: node_js
node_js: node
cache: yarn
install:
  - yarn
script:
  - yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_b1a3d0fee02e_key -iv $encrypted_b1a3d0fee02e_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avn --delete $TRAVIS_BUILD_DIR/dist/ $HOST_USER/$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master
